separate messages file.
hariharanBala-CBT/strongr-web pull request #7
Opened 2024-06-14 07:15 UTC by TharunCBT

- Added a separate messages.py file to get the success and error messages from it.
- Removed commented out code and some empty extra lines.

2024-06-17 03:54 UTC, rugvedcbt approved these changes

2024-06-17 06:15 UTC, ramprasadm-CBT commented on backend/base/views.py
> +            messages.success(self.request, SUCCESS_MESSAGES.get['create_unavailable_slot'])
why change to square brackets?

2024-06-17 06:15 UTC, ramprasadm-CBT commented on backend/base/views.py
> +                messages.success(self.request, SUCCESS_MESSAGES['delete_unavailable_slot'])
Why not .get and why square brackets?

2024-06-17 06:16 UTC, ramprasadm-CBT commented on backend/base/views.py
> +            messages.success(self.request, SUCCESS_MESSAGES.get['create_additional_slot'])
Square bracket reason?

2024-06-17 06:16 UTC, ramprasadm-CBT commented on backend/base/views.py
> +                messages.success(self.request, SUCCESS_MESSAGES.get['delete_additional_slot'])
change in syntax. reason?

2024-06-17 06:17 UTC, ramprasadm-CBT commented on backend/base/views.py
> +            messages.success(request, SUCCESS_MESSAGES.get['create_slot'])
syntax change in success message retrieval. why?

2024-06-17 06:18 UTC, ramprasadm-CBT commented on backend/base/views.py
> +            return JsonResponse({'status': 'success', 'message': SUCCESS_MESSAGES.get('update_workingdays')})
changed back to usual syntax. follow one pattern.

2024-06-17 06:19 UTC, ramprasadm-CBT commented on backend/frontend/src/store.js
> -  composeWithDevTools((applyMiddleware(...middleware))),
comment it when you push. in local we can uncomment it for development needs.

2024-06-17 06:21 UTC, ramprasadm-CBT commented on backend/base/messages.py
> +# messagespy
Thats a commented out file name for my reference in note-pad. i forgot to remove it while pushing. No need for change in it.

2024-06-17 06:22 UTC, ramprasadm-CBT requested changes
Please change the mentioned below. Mainly syntax changes. Minor fix

2024-06-17 08:25 UTC, rugvedcbt requested changes

2024-06-17 08:25 UTC, rugvedcbt commented on backend/base/templates/slot-list.html
>      </script>
check this function whether its working. constant is defined with $ symbol, but used without symbol inside function.

2024-06-18 09:47 UTC, ramprasadm-CBT approved these changes

2024-06-19 05:44 UTC, rugvedcbt commented on backend/base/templates/slot-list.html
> +     <style>
external css file can be used

2024-06-19 05:44 UTC, rugvedcbt commented on backend/base/templates/slot_location.html
> +            }
can use external css files.

2024-06-19 05:44 UTC, rugvedcbt commented on backend/base/templates/temp-slots-list.html
> +        }
can use external css files.

2024-06-19 05:44 UTC, rugvedcbt commented on backend/base/templates/temp-slots-list.html
>          .popup {
can use external css files.

2024-06-19 05:45 UTC, rugvedcbt commented on backend/base/templates/unavailable-slot-list.html
>          .popup {
can use external css files.

2024-06-19 05:45 UTC, rugvedcbt commented on backend/base/templates/update_slot.html
> +
can use external css files.

2024-06-19 05:46 UTC, rugvedcbt reviewed
can use external css files instead of internal css in html wherever its possible.

2024-06-19 09:26 UTC, murucbt reviewed
Small Nits.

2024-06-19 09:26 UTC, murucbt commented on backend/base/static/css/slot-list.css
> +#successAlert p {
Can you try like below ?

```
#successAlert {
  position: fixed;
  top: 70px;
  right: 20px;
  background-color: #323231;
  color: white;
  padding: 10px 20px;
  border-radius: 5px;
  z-index: 1050;

  p {
    text-align: center;
    margin: 0;
  }
}
```

2024-06-19 09:26 UTC, murucbt commented on backend/base/messages.py
> +    'orglocation_status' : 'Organization location status updated sucessfully',
Seems typo. Check other places too.

2024-06-20 08:41 UTC, rugvedcbt commented on backend/base/static/css/update_slot.css
> +}
.popup {
  display: none;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-19%, -27%);
  background-color: #fff;
  padding: 40px 40px;
  border: 2px solid #888;
  border-radius: 5px;
  z-index: 9999;
  button {
  width: 25%;
  padding: 5px 10px;
  border: none;
  border-radius: 5px;
  color: white;
  background: #007bff;
  text-align: center;
  font-size: 16px;
}
h2 {
  margin-bottom: 15px;
}}
can use css like this

2024-06-20 08:42 UTC, rugvedcbt approved these changes

2024-06-20 08:58 UTC, TharunCBT commented on backend/base/static/css/update_slot.css
> +}
Changed it!!

2024-06-20 09:51 UTC, merged