fix: validate phone for login
hariharanBala-CBT/strongr-web pull request #8
Opened 2024-06-14 07:58 UTC by rugvedcbt

Validating phone number of a customer while logging in using number.Showing error toasts if user doesn't exist in database with the given number.

2024-06-17 06:24 UTC, ramprasadm-CBT commented on backend/frontend/src/screens/UpdateProfileScreen.js
>    }, [userUpdateSuccess, navigate, dispatch, userUpdateError, submit]);
Ascending order please.

2024-06-17 06:26 UTC, ramprasadm-CBT requested changes
please make the following change.

2024-06-17 06:31 UTC, ramprasadm-CBT approved these changes

2024-06-18 05:00 UTC, TharunCBT approved these changes
Next time while commiting check if there is any extra lines left out.

2024-06-18 09:40 UTC, ramprasadm-CBT approved these changes

2024-06-19 09:50 UTC, murucbt approved these changes

2024-06-19 09:58 UTC, merged